version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: olk-darwin
    main: ./cmd/olk
    binary: olk
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/rlrghb/olkcli/internal/cmd.Version={{.Version}}
      - -X github.com/rlrghb/olkcli/internal/cmd.Commit={{.Commit}}
      - -X github.com/rlrghb/olkcli/internal/cmd.Date={{.Date}}

archives:
  - id: olk
    ids:
      - olk-darwin
    name_template: "olk_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

release:
  disable: true
